### ISSUE TITLE
[버그]: ad0834cd-4f98-4475-af00-b1bc3a2c3366

### ISSUE THREAD

**Issue by heroryu** [penggin/pengbot_support#24]
### 어느 명령어에서 버그가 발생하나요?

/play

### 어떤 버그가 발생하나요?

어플리케이션이 응답하지 않음 이라고 뜸
/fix 도 마찬가지

### 원래는 어떻게 작동해야했나요?

노래 어플리케이션이 정상 작동함

### 이 버그가 발생한 기기는 무었인가요?

- [X] PC (컴퓨터)
- [ ] Mobile (휴대폰)
- [ ] Web (웹버전)

### 디스코드 버전

10.0.19045

**Comment by penggin** [comment]
엇 답장이 늦었네요. 해당 시간에 발생한 오류는 서버 요청 과다로 인한 것으로 보입니다. 아무래도 후원등을 받지 않고있다보니, 서버
용량에 제한이 있네요... 조만간 최적화 진행 예정입니다!

2023년 2월 13일 (월) 오후 9:32, heroryu ***@***.***>님이 작성:
