### ISSUE TITLE
[버그]: 그냥 유튜브 링크 올리니까 한 5분~10분 뒤에 노래가 재생됬습니다

### ISSUE THREAD

**Issue by JIMI590** [penggin/pengbot_support#25]
### 어느 명령어에서 버그가 발생하나요?

/fix 해도 안고쳐 집니다

### 어떤 버그가 발생하나요?

그냥 유튜브 링크 올리니까 한 5분~10분 뒤에 노래가 재생됬습니다
술팽봇이 렉걸리는거 같은데 여러 서버에서 바로바로 작동이 되는게 아니라 몇분뒤에 작동해서 명령어도 좀 늦게 쳐져서 렉이 걸리는게 아닌가 싶습니다
에러코드 : dc8b0c24-0e0f-4621-ba46-7665aa7b0ee7 여기도 안되고 , 다른서버도 엄청 늦게 노래가 재생됩니다 

### 원래는 어떻게 작동해야했나요?

원래는 링크 올리면 바로 노래가 재생되야 하는데 안됩니다. 제대로 작동하는건지도 모르겠습니다.

### 이 버그가 발생한 기기는 무었인가요?

- [X] PC (컴퓨터)
- [ ] Mobile (휴대폰)
- [ ] Web (웹버전)

### 디스코드 버전

가장 최신버전..?

**Comment by penggin** [comment]
해당 이슈를 인지하였으며, 원인 파악 진행중입니다. 제보해주셔서 감사드립니다!

2023년 2월 16일 (목) 오전 12:29, JIMI590 ***@***.***>님이 작성:

**Comment by penggin** [comment]
issue resolved.
