### ISSUE TITLE
[버그]: 

### ISSUE THREAD

**Issue by haechan1119** [penggin/pengbot_support#26]
### 어느 명령어에서 버그가 발생하나요?

에러코드 : e9c63537-22b5-4d2b-ab87-327af005b24d

### 어떤 버그가 발생하나요?

자가진단등록 오류났습니다

### 원래는 어떻게 작동해야했나요?

처음부터 자가진단등록 오류났습니다

### 이 버그가 발생한 기기는 무었인가요?

- [X] PC (컴퓨터)
- [ ] Mobile (휴대폰)
- [ ] Web (웹버전)

### 디스코드 버전

discord(32비트)

**Comment by penggin** [comment]
자가진단 서비스는 지원종료 되었습니다.
